require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'FoodOrder' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

  target 'FoodOrderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end

    # ADDITION #
    # arm64 disable
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'FoodOrder-tvOS' do
  # Pods for FoodOrder-tvOS

  target 'FoodOrder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# ADDITION #
# arm64 disable
files = Dir.glob("*.xcodeproj")
proj_file = files[0]

project = Xcodeproj::Project.open(proj_file)
project.native_targets.each do |target|
  puts 'native_targets'
  target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS"] = "arm64"
    config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
  end
end
project.save







