export const applePayMerchantId = 'merchant.newline'; 
// export const merchantId = 'MLTC2HS6DWXPK,MLV3K49BKW5BC,ML87YMVSPK6YM';
// export const merchantId = 'YHX6SCJQGQ9TX'; // blended
// export const merchantId = 'MLWYX54P9CP69';
// export const merchantId = '28FA98KV9WPQN'; // manhattan bagel
// export const merchantId = '6YX6XBC18DRY7'; // holding
// export const merchantId = 'T8GKVD7S1VNSB'; // bintang
// export const merchantId = '3T39CEB8C2JT0'; // pomona
// export const merchantId = 'ML73ZGH8VRT06'; // jill's pizza
// export const merchantId = '3F4008G1DY83K'; // apollo burgers

// export const merchantId = 'NZMKRJ5N0EC07' // Mama
// export const merchantId = 'ERQT5AX6H7WRT' // bossvegan
// export const merchantId = 'TQ7DHEVRSS878' // ruffel
// export const merchantId = 'MLYAEM5MDDHQ5' // elpasso pizza
// export const merchantId = '7KRDV52JJEQN9' // mochanut
// export const merchantId = 'EGSVGE3FJY5P8' // blackbeards
// export const merchantId = 'KHVYET5G3HGZB' // bajagrill
// export const merchantId = 'FZZE21GVTE7P9' // leeshawaiian
// export const merchantId = 'WSTQMBHPXS08T' // maxssteaks
// export const merchantId = '9ZCH69X98QVNZ' // harmonytea
// export const merchantId = 'J66AC69R3DYTN' // benne
// export const merchantId = '4MHFDAYGG4XDF' // brewja
 
// export const merchantId = 'MLYPK7NV4D50D' // greenspace
// export const merchantId = 'BMHJBXY5WG8DX' // tastywok
// export const merchantId = 'BMHJBXY5WG8DX' // tastywok
// export const merchantId = '5VC75VMMQZ8RJ' // tokava
// export const merchantId = 'QMT1Z2R20YPNT' // nextlevel
// export const merchantId = '4YFCVR5DJ64RN' // grillatlisbon
// export const merchantId = 'MLGF4AGWF2QJV' // kufta
// export const merchantId = '5G4H9PCX200QK' // greenology
// export const merchantId = 'CFHTXBH1DY5R4' // whitneysgift
// export const merchantId = '25RG08Z4FK53D' // lindseystreet
// export const merchantId = 'VQW2WWKSS14QW' // suitplus
// export const merchantId = '7QKY4AZ25X7E4' // veroni

// export const merchantId = '2M84C7DYHTMT2' // ccsweets
// export const merchantId = 'VZ1BNYB6338RN' // thaimeup
// export const merchantId = 'WNC2XRJ38NFQX' // Chompsky's
// export const merchantId = '0VY8JAS28X52E' // Waypoint coffee
// export const merchantId = 'C4RDTZ1990MK0' // Guest house
// export const merchantId = 'XKTAPYZFDX2RR' // truestone
// export const merchantId = 'HCGF8GNKJC9GM' // vampirepenguin 
// export const merchantId = '2X37PZXS866SX' // flippinsweet  
// export const merchantId = 'MLTA4FWE5XS8N' // zizikis
// export const merchantId = 'SCK0DT6J6Q5WG' // sugarbiscuits
// export const merchantId = 'TNXWYMHF0H7CB' // thegrill
// export const merchantId = 'MLSRBH06F5KZK' // evettes
// export const merchantId = '7Q05THM9PAWST' // meatings
// export const merchantId = 'VJ5R1YZPW1FJS' // goldengloves
// export const merchantId = 'Z6K4JHADWJJDF' // theaztec
// export const merchantId = 'TFBAB4XA1GD19' // isleofcoffee
 
// export const merchantId = 'WTFNTHYX2BSBM' // urban
// export const merchantId = 'DXV8C7D4CRB46' // Leaves
// export const merchantId = 'AXEZBCY8MYR42' // TAP NYC SN97R8G6WBBXV
// export const merchantId = 'VNFK59JC44F48,SN97R8G6WBBXV' // TAP NYC LES
// export const merchantId = '8E0PF658WS8MA' // Coffee Dose
// export const merchantId = '1DQZCFT55J9JJ' // falafel boy
// export const merchantId = '0GHMWJCGT9DWH' // MT
// export const merchantId = 'QBTNJT8Z3P6VJ' // my mustard seed
// export const merchantId = 'YF40G865908Y9' // bon bon
// export const merchantId = 'FSEA6X4AJK14H' // eats and treats

// export const merchantId = 'T1YZDBB1KTRW8' // The Pour Farmer
// export const merchantId = 'ML67B552KXFHH' // hushh
// export const merchantId = 'BQ5PD2VJARQ3C' // Reversing The Triangle
// export const merchantId = 'JK0PXWY5X216E' // Daily Kombucha
// export const merchantId = '2KZ509K0EGT3T' // THINK Coffee
// export const merchantId = '8P7N0ZW0FTXWN' // stations
// export const merchantId = 'T8SVTADP6AHX5' // fiddlescoffee

// export const merchantId = 'HNSA49EGPZNVQ' // Hawaiian Coffee
// export const merchantId = 'TYHND0W0P66YA' // Genos Pizza
// export const merchantId = '33723Q7B5Y0TZ' // Shy bear
// export const merchantId = 'MLBSYGX2DXA7X' // 3 junction
// export const merchantId = 'SGYK6P3JP26MK' // Kino coffee
// export const merchantId = '1Y1SQPBY7ESVH' // Yellow vase
// export const merchantId = 'W3ND46RSXGJ40' // Meta burger
// export const merchantId = '102PE0979685F' // Sip stir

// export const merchantId = 'Z6K4JHADWJJDF' // az
// export const merchantId = 'BXPVGA8RG4WM2' // POLLO 
// export const merchantId = 'YTGT0XDFFZR3X' // loaded
export const merchantId = '6D6Z5BD6F1WBK' // DEMO STORE
// export const merchantId = 'MLZVJ8269DZ7B' // Gooies
// export const merchantId = 'ML7PGHQSW6PZZ' // delhi palace
// export const merchantId = '92C72FGJQTD8F' // Sabor
// export const merchantId = '9B4N93XGKMM7Y,28B0A7121J9CA' // KevaJuice
// export const merchantId = 'MLW2BXF47VGG0' // lazy
// export const merchantId = 'AH4NACF77MVQC' // Two Cricks
// export const merchantId = '851CJDT65TESY' // fit
// export const merchantId = '7MXQQ6W068W3Z' // MasalaWak
// export const merchantId = 'MLCZE0BCP4D6G' // Jora
// export const merchantId = 'ML49KZPGEMY9X' // CBD - retail
// export const merchantId = '1X8RT2HGTYS9W' // Juicery
// export const merchantId = 'QJ3G53Q0P98X0' // reptails
// export const merchantId = '3WHZ6T846KPJN' // open box
// export const merchantId = 'QJ3G53Q0P98X0' // w
// export const merchantId = 'MLX3KCWXZ879B' // Passionate's UrbanHOOD
// export const merchantId = '6SMW08N6PV5M0' // Devs
// export const merchantId = 'MLCWVSE8CCXKC' // Dexter
// export const merchantId = '1X8RT2HGTYS9W' // the juicery
// export const merchantId = '950S31R8H2D2W' // Dog inn pub UK
// export const merchantId = '7AH5SS46Q418A' // shotcaller
// export const merchantId = '6F18MFTF6NHM6' // peterson 
// export const merchantId = 'MLKDGT6MWZ8AV' // goosbump 
// export const merchantId = 'SGYK6P3JP26MK' // chai 