export const NAME = "fooddata";

export type State = {
  categories: null,
  variations: null,
  modifiers: null,
  foods: [],
  taxes: [],
  secondaryCategories: {},
  secondaryVariations: {},
  secondaryModifiers: {},
  secondaryFoods: {},
  secondaryTaxes: {},

  currentLocation: any,
  locations: [],
  appSettings: any,

  customerCards: [],

  favorite: {},
  orders: {},
  isLoading: false,
  seletedCategory: any,
  cartData: object,

  currentMerchant: '',
  masterMerchant: '',

  order: {net_amounts: {}, discounts: [], line_items: [], rewards: [], taxes: [], total_discount_money: { amount: 0}, total_money: { amount: 0}, recommendations: { items: [] }},
  locationId: '',
  ordaId: 0,
  ordaOperations: [],
  cartItems: [],
  cartSubtotal: 0,
  unstagedSubtotal: 0,
  cartTax: 0,
  cartTotal: 0,
  totalAmount: 0,
  currency: { id: 'USD', symbol: '$' },
  account: { name: 0, mobile: 0, loyalty: 0},
  orderTime: 'ASAP',
  orderAheadTimes: {},
  isStoreOpen: true,
  diningType: 'Takeout',
  orderPoints: 0,
  squareOrderId: null,
  customer: 0,
  payment: 0,
  paymentErrors: {},
  loyalty: 0,
  discounts: 0,
  appliedReward: 0,
  upvotes: 0,
  styles: 0,
  table: 0,
  bean: 0,
  rewardErrors: 0,
  redemption: 0,
  redemptionErrors: 0,
  couponCode: 0,
  counts: 0,

  storePause: false,

  orderAt: null,
  fulfillmentType: null,
};
